server:
  port: 8761
  compression:
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/mss-config-repo
      enabled: true
management:
  security:
    enabled: false