server:
  port: 8080
  compression:
    enabled: true
eureka:
  instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      nonSecurePort: ${server.port}
      hostname: do
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
spring:
  application:
    name: mss-app-layer